### ISSUE TITLE
bug: rabbitmq channel connection is not restored

### ISSUE THREAD

**Issue by ruscon** [Surnet/graphql-amqp-subscriptions#52] opened 2024-02-12 10:41 UTC
```
IllegalOperationError: Channel closed
    at Channel.<anonymous> (/app/dist/node_modules/.pnpm/amqplib@0.10.3/node_modules/amqplib/lib/channel.js:159:11)
    at C._rpc (/app/dist/node_modules/.pnpm/amqplib@0.10.3/node_modules/amqplib/lib/channel.js:141:8)
    at /app/dist/node_modules/.pnpm/amqplib@0.10.3/node_modules/amqplib/lib/channel_model.js:57:19
    at node:internal/util:442:7
    at new Promise (<anonymous>)
    at node:internal/util:428:12
    at Channel.rpc (/app/dist/node_modules/.pnpm/amqplib@0.10.3/node_modules/amqplib/lib/channel_model.js:58:7)
    at Channel.assertExchange (/app/dist/node_modules/.pnpm/amqplib@0.10.3/node_modules/amqplib/lib/channel_model.js:118:17)
    at AMQPPublisher.publish (/app/dist/node_modules/.pnpm/graphql-amqp-subscriptions@2.0.0_amqplib@0.10.3_graphql-subscriptions@2.0.0_graphql@16.8.1/node_modules/graphql-amqp-subscriptions/dist/amqp/publisher.js:24:23)
```

I checked locally, it is easy to reproduce:
1. Create an active graphql subscription 
2. Restart the rabbitmq server
3. Submit an event you've signed up for - you must get the error.

I see there was some discussion on this topic a few years ago https://github.com/Surnet/graphql-amqp-subscriptions/issues/16

**Comment by chdanielmueller** [comment] 2024-11-08 09:46
Duplicate of #16

Feel free to submit a PR for Channel reopening

**Closed by chdanielmueller** 2024-11-08 09:46 UTC
